{% set name = "awkward0" %}
{% set version = "0.15.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward0-{{ version }}.tar.gz
  sha256: 156e6e338c56d857a7bb53c4fcc8b0b2592a3470eff0d854e6d68777986359ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python =2.7|>=3.5
  run:
    - numpy >=1.13.1
    - python =2.7|>=3.5

test:
  imports:
    - awkward0
    - awkward0.array
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-0.x
  summary: Manipulate arrays of complex data structures as easily as Numpy.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
